# vim:set ft=dockerfile:

# Use CERN's official centos7
FROM gitlab-registry.cern.ch/lhcb-docker/os-base/centos7-hepos:latest

#################
# Update system #
#################

# add CERN CentOS yum repo
ADD http://linux.web.cern.ch/linux/centos7/CentOS-CERN.repo /etc/yum.repos.d/CentOS-CERN.repo
ADD http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern /tmp/RPM-GPG-KEY-cern

RUN /usr/bin/rpm --import /tmp/RPM-GPG-KEY-cern && \
    /bin/rm /tmp/RPM-GPG-KEY-cern

RUN yum update -y && \
    yum clean all && rm -rf /var/cache/yum


####################
# Add dev packages #
####################

RUN yum install -y \
    rpm-build openssl-devel libXpm-devel \
    glib2-devel afs_tools hepix \
    xorg-x11-xauth glibc-static libXp-devel libXi-devel \
    xorg-x11-util-macros libjpeg-turbo-devel libXaw libXaw-devel \
    xorg-x11-server-Xvfb createrepo symlinks libxslt \
    CERN-CA-certs \
    glibc-devel.x86_64 \
    libxslt-devel libgit2-devel \
    xz-devel lcov \
    bzip2 zip \
    python-pip python-devel \
    distcc ccache make cmake3 gcc-c++ \
    git subversion \
    zsh tmux emacs vim \
    && yum clean all && rm -rf /var/cache/yum

# Update pip
RUN pip install --upgrade pip setuptools


#########################
# Install LHCb packages #
#########################

RUN mkdir -p /opt/lhcb

RUN pip install lbinstall

RUN lbinstall --root=/opt/lhcb install LBSCRIPT CMT COMPAT
RUN lbinstall --root=/opt/lhcb install DAVINCI_v42r8p1_x86_64_centos7_gcc62_opt


###############################
# Load default configurations #
###############################

ADD ./zshrc /home/physicist/.zshrc
ADD ./tmux.conf /home/physicist/.tmux.conf

# Make sure 'cmake' is linked to 'cmake3'
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake


########################
# Make our own DaVinci #
########################

RUN mkdir -p /build
WORKDIR /build

# Setup ENVs
ENV LD_LIBRARY_PATH="/opt/lhcb/lcg/releases/gcc/6.2.0/x86_64-centos7/lib64:${PATH}"

RUN . /opt/lhcb/LbLogin.sh && \
    git config --global user.name "Physicist" && \
    git config --global user.email "lhcb@physics.umd.edu" && \
    lb-dev DaVinci/v42r8p1 && cd DaVinciDev_v42r8p1 && \
    git lb-use Analysis && \
    git lb-checkout Analysis/v18r8p1 Phys/DecayTreeTuple && \
    make configure && make install

# Install the compiled files to existing DaVinci
RUN cp -r ./DaVinciDev_v42r8p1/InstallArea/x86_64-centos7-gcc62-opt/lib/*.so \
        /opt/lhcb/lhcb/DAVINCI/DAVINCI_v42r8p1/InstallArea/x86_64-centos7-gcc62-opt/lib/ && \
    cp -r ./DaVinciDev_v42r8p1/InstallArea/x86_64-centos7-gcc62-opt/python \
        /opt/lhcb/lhcb/DAVINCI/DAVINCI_v42r8p1/InstallArea/x86_64-centos7-gcc62-opt/


#############################
# Bootstrap user permission #
#############################

# Add the bootstrap script
ADD ./bootstrap.sh /usr/local/bin

# Make UID and GID ENV
ENV UID 1000
ENV GID 985

CMD ["/usr/local/bin/bootstrap.sh"]
