# vim:set ft=dockerfile:

ARG DAVINCI_VERSION=v45r3
ARG GCC_DEPENDENCY=x86_64_centos7_gcc8_opt

FROM umdlhcb/centos7-base:clion

ARG DAVINCI_VERSION
ARG GCC_DEPENDENCY

# Install DaVinci
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install DAVINCI_${DAVINCI_VERSION}_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# Install additional DaVinci dependency
# FIXME: This is a bug and should be reported upstream
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install LCG_96b_six_1.12.0_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# NOTE: These entries needs to be updated on each DaVinci update
ADD ./envset.sh /usr/local/bin
RUN echo ". /usr/local/bin/envset.sh" >> /home/physicist/.zshrc
