# vim:set ft=dockerfile:

ARG DAVINCI_VERSION=v44r10
ARG ANALYSIS_VERSION=v20r9
ARG GCC_DEPENDENCY=x86_64-centos7-gcc62-opt

FROM umdlhcb/lhcb-stack-cc7:DaVinci-${DAVINCI_VERSION}

# Make the ARG values defined in the previous stage accessible
ARG DAVINCI_VERSION
ARG ANALYSIS_VERSION
ARG GCC_DEPENDENCY

##################
# Extend DaVinci #
##################

# I know, it's a bad idea to put token inside a docker. But this one is restricted.
ARG GITLAB_TOKEN=berHk8dhDeVYKCSjhk9x

# Setup ENVs
ENV PATH="/opt/lhcb/lcg/releases/gcc/6.2.0/x86_64-centos7/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/lhcb/lcg/releases/gcc/6.2.0/x86_64-centos7/lib64:${LD_LIBRARY_PATH}"

RUN mkdir -p /build
WORKDIR /build

RUN . /opt/lhcb/LbLogin.sh && \
    git config --global user.name "Physicist" && \
    git config --global user.email "lhcb@physics.umd.edu" && \
    lb-dev DaVinci/${DAVINCI_VERSION} && cd DaVinciDev_${DAVINCI_VERSION} && \
    git lb-use Analysis && \
    git lb-use SemileptonicCommonTools https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-slb/SemileptonicCommonTools.git && \
    git lb-checkout Analysis/${ANALYSIS_VERSION} Phys/DecayTreeTuple && \
    git lb-checkout SemileptonicCommonTools/master Phys/SemileptonicCommonTools

# Clone TupleToolSemiLeptonic
RUN git clone https://github.com/umd-lhcb/TupleToolSemiLeptonic.git && \
    cp TupleToolSemiLeptonic/*.{cpp,h} /build/DaVinciDev_${DAVINCI_VERSION}/Phys/DecayTreeTuple/src && \
    cp TupleToolSemiLeptonic/CMakeLists.txt /build/DaVinciDev_${DAVINCI_VERSION}/Phys/DecayTreeTuple

# Compile TupleToolApplyIsolation & other stuff
RUN . /opt/lhcb/LbLogin.sh && \
    cd DaVinciDev_${DAVINCI_VERSION} && \
    make configure && make

# Cleanups
RUN rm -rf /build/TupleToolSemiLeptonic


########################
# Update ENV variables #
########################

# Update $PATH in zsh
RUN echo "export PATH=/build/DaVinciDev_${DAVINCI_VERSION}/build.${GCC_DEPENDENCY}:\$PATH" >> /home/physicist/.zshrc
