# vim:set ft=dockerfile:

ARG DAVINCI_VERSION=v45r3
ARG GCC_DEPENDENCY=x86_64_centos7_gcc8_opt

FROM umdlhcb/centos7-base:dev

ARG DAVINCI_VERSION
ARG GCC_DEPENDENCY

# Install DaVinci
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install DAVINCI_${DAVINCI_VERSION}_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# Install additional DaVinci dependency
# FIXME: This is a bug and should be reported upstream
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install LCG_96b_six_1.12.0_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# NOTE: These entries needs to be updated on each DaVinci update
# Source LHCb environment setter on login
RUN echo ". /opt/lhcb/LbLogin.sh" >> /home/physicist/.zshrc && \
    echo ". /opt/lhcb/lcg/releases/ROOT/6.18.04-c767d/x86_64-centos7-gcc8-opt/bin/thisroot.sh" >> /home/physicist/.zshrc

# Environmental variables
ENV CMTCONFIG x86_64-centos7-gcc8-opt
ENV PATH="/opt/lhcb/lcg/releases/gcc/8.3.0/x86_64-centos7/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/lhcb/lcg/releases/gcc/8.3.0/x86_64-centos7/lib64:${LD_LIBRARY_PATH}"

ENV CC="/opt/lhcb/lcg/releases/gcc/8.3.0/x86_64-centos7/bin/gcc"
ENV CXX="/opt/lhcb/lcg/releases/gcc/8.3.0/x86_64-centos7/bin/g++"
ENV CMAKE_PREFIX_PATH="/opt/lhcb/lcg/releases/Boost/1.70.0-eebf1/x86_64-centos7-gcc8-opt:${CMAKE_PREFIX_PATH}"
ENV CMAKE_PREFIX_PATH="/opt/lhcb/lcg/releases/HepMC/2.06.10-1a364/x86_64-centos7-gcc8-opt:${CMAKE_PREFIX_PATH}"

# Install CLion
WORKDIR /tmp

RUN curl https://download-cf.jetbrains.com/cpp/CLion-2019.2.5.tar.gz --output clion.tar.gz && \
    tar -xzf clion.tar.gz -C /opt && \
    rm -rf /tmp/*
RUN yum install -y libXtst
