# vim:set ft=dockerfile:

ARG DAVINCI_VERSION=v42r8p1
ARG ANALYSIS_VERSION=v18r8p1
ARG GCC_DEPENDENCY=x86_64-centos7-gcc62-opt

FROM umdlhcb/lhcb-stack-cc7:DaVinci-${DAVINCI_VERSION}

# Make the ARG values defined in the previous stage accessible
ARG DAVINCI_VERSION
ARG ANALYSIS_VERSION
ARG GCC_DEPENDENCY

############
# Backport #
############

# Cleanups
RUN rm -rf /tmp/* && \
    rm -rf /opt/lhcb/var/cache

# Install 'cmake3' and make it default
RUN yum remove -y cmake && yum install -y cmake3 \
    && yum clean all && rm -rf /var/cache/yum

RUN ln -s /usr/bin/cmake3 /usr/bin/cmake


##################
# Extend DaVinci #
##################

RUN mkdir -p /build
WORKDIR /build

RUN . /opt/lhcb/LbLogin.sh && \
    git config --global user.name "Physicist" && \
    git config --global user.email "lhcb@physics.umd.edu" && \
    lb-dev DaVinci/${DAVINCI_VERSION}

# Check out TupleToolSemiLeptonic
RUN . /opt/lhcb/LbLogin.sh && \
    cd DaVinciDev_${DAVINCI_VERSION} && \
    git lb-use TupleToolSemiLeptonic https://github.com/umd-lhcb/TupleToolSemiLeptonic.git && \
    git lb-checkout TupleToolSemiLeptonic/0.1.1 Phys/TupleToolSemiLeptonic

# Compile TupleToolApplyIsolation & other stuff
RUN . /opt/lhcb/LbLogin.sh && \
    cd DaVinciDev_${DAVINCI_VERSION} && \
    make configure && make


########################
# Update ENV variables #
########################

# Update $PATH in zsh
RUN echo "export PATH=/build/DaVinciDev_${DAVINCI_VERSION}/build.${GCC_DEPENDENCY}:\$PATH" >> /home/physicist/.zshrc
