# vim:set ft=dockerfile:

ARG DAVINCI_VERSION=v45r3
ARG GCC_DEPENDENCY=x86_64_centos7_gcc8_opt

FROM umdlhcb/centos7-base:clion

ARG DAVINCI_VERSION
ARG GCC_DEPENDENCY

# Install DaVinci
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install DAVINCI_${DAVINCI_VERSION}_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# Install bzip2, which is used for DDDB update
RUN yum install -y bzip2 \
    && yum clean all && rm -rf /var/cache/yum

# Install missing DaVinci dependencies
RUN mkdir -p /tmp/lbinstall-tmp && \
    mkdir -p /tmp/lbinstall-cache
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb --tmp_dir=/tmp/lbinstall-tmp --rpmcache=/tmp/lbinstall-cache \
        install LCG_96b_six_1.12.0_${GCC_DEPENDENCY} && \
    # Cleanups
    rm -rf /tmp/*

# Install CondDB
# FIXME: Bad practice to embed token
ARG GITLAB_TOKEN=berHk8dhDeVYKCSjhk9x
RUN cd /opt/lhcb/lhcb && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/STCOND.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/VELOCOND.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/ONLINE.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/DQFLAGS.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/SIMCOND.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/LHCBCOND.git && \
    git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@gitlab.cern.ch/lhcb-conddb/DDDB.git
ENV GITCONDDBPATH "/opt/lhcb/lhcb"

# FIXME: Workaround missing cmake config
ADD ./toolchain.cmake /opt/lhcb/lhcb/DAVINCI/DAVINCI_${DAVINCI_VERSION}

# NOTE: These entries needs to be updated on each DaVinci update
ADD ./envset.sh /usr/local/bin
RUN echo ". /usr/local/bin/envset.sh" >> /home/physicist/.zshrc
