# vim:set ft=dockerfile:

FROM ypsunumd/lhcb-stack-cc7:DaVinci-v42r8p1

########################
# Make our own DaVinci #
########################

# I know, it's a bad idea to put token inside a docker. But this one is restricted.
ENV GITLAB_TOKEN berHk8dhDeVYKCSjhk9x

RUN mkdir -p /build
WORKDIR /build

RUN . /opt/lhcb/LbLogin.sh && \
    git config --global user.name "Physicist" && \
    git config --global user.email "lhcb@physics.umd.edu" && \
    lb-dev DaVinci/v42r8p1 && cd DaVinciDev_v42r8p1 && \
    git lb-use Analysis && \
    git lb-use SemileptonicCommonTools https://oauth2:$GITLAB_TOKEN@gitlab.cern.ch/lhcb-slb/SemileptonicCommonTools.git && \
    git lb-checkout Analysis/v18r8p1 Phys/DecayTreeTuple && \
    git lb-checkout SemileptonicCommonTools/master Phys/SemileptonicCommonTools

# Clone TupleToolSemiLeptonic
RUN git clone https://github.com/umd-lhcb/TupleToolSemiLeptonic.git && \
    cp TupleToolSemiLeptonic/*.{cpp,h} /build/DaVinciDev_v42r8p1/Phys/DecayTreeTuple/src && \
    cp TupleToolSemiLeptonic/CMakeLists.txt /build/DaVinciDev_v42r8p1/Phys/DecayTreeTuple

# Compile TupleToolApplyIsolation & other stuff
RUN . /opt/lhcb/LbLogin.sh && \
    cd DaVinciDev_v42r8p1 && \
    make configure && make

# Cleanups
RUN rm -rf /build/TupleToolSemiLeptonic


########################
# Update ENV variables #
########################

# Update $PATH in zsh
RUN echo "export PATH=/build/DaVinciDev_v42r8p1/build.x86_64-centos7-gcc62-opt:\$PATH" >> /home/physicist/.zshrc
