# vim:set ft=dockerfile:

# Use CERN's official centos7
FROM gitlab-registry.cern.ch/lhcb-docker/os-base/centos7-hepos:latest

#################
# Update system #
#################

# add CERN CentOS yum repo
ADD http://linux.web.cern.ch/linux/centos7/CentOS-CERN.repo /etc/yum.repos.d/CentOS-CERN.repo
ADD http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern /tmp/RPM-GPG-KEY-cern

RUN /usr/bin/rpm --import /tmp/RPM-GPG-KEY-cern && \
    /bin/rm /tmp/RPM-GPG-KEY-cern

RUN yum update -y && \
    yum clean all && rm -rf /var/cache/yum


####################
# Add dev packages #
####################

RUN yum install -y \
    rpm-build openssl-devel libXpm-devel \
    glib2-devel afs_tools hepix \
    xorg-x11-xauth glibc-static libXp-devel libXi-devel \
    xorg-x11-util-macros libjpeg-turbo-devel libXaw libXaw-devel \
    xorg-x11-server-Xvfb createrepo symlinks libxslt \
    CERN-CA-certs \
    glibc-devel.x86_64 \
    libxslt-devel libgit2-devel \
    xz-devel lcov \
    bzip2 zip \
    python-pip python-devel \
    distcc ccache make cmake gcc-c++ \
    git subversion \
    zsh tmux emacs vim \
    && yum clean all && rm -rf /var/cache/yum

# Update pip
RUN pip install --upgrade pip setuptools


#########################
# Install LHCb packages #
#########################

RUN mkdir -p /opt/lhcb

RUN pip install lbinstall

RUN lbinstall --root=/opt/lhcb install LBSCRIPT CMT COMPAT
RUN lbinstall --root=/opt/lhcb install DAVINCI_v42r8p1_x86_64_centos7_gcc62_opt


###############################
# Load default configurations #
###############################

ADD ./zshrc /home/physicist/.zshrc
ADD ./tmux.conf /home/physicist/.tmux.conf


#############################
# Bootstrap user permission #
#############################

# Add the bootstrap script
ADD ./bootstrap.sh /usr/local/bin

# Make UID and GID ENV, also delete 'builder'
ENV UID 1000
ENV GID 985

CMD ["/usr/local/bin/bootstrap.sh"]
