# vim:set ft=dockerfile:

FROM umdlhcb/centos7-base


##################
# Install neovim #
##################

WORKDIR /tmp

RUN yum install -y \
    libtool gettext xsel \
    && yum clean all && rm -rf /var/cache/yum

RUN git clone --depth 1 --branch v0.4.3 https://github.com/neovim/neovim.git
RUN cd neovim && \
    make CMAKE_BUILD_TYPE=Release && \
    make install && \
    rm -rf /tmp/*

# Install neovim python 3 lib
RUN pip3 install pynvim==0.3.2


#######################
# Install vim plugins #
#######################

WORKDIR /tmp

RUN git clone --depth 1 --branch 0.1.2 https://github.com/ypsun-umd/neovim-config-standalone.git && \
    cd neovim-config-standalone && \
    git submodule update --init --recursive && \
    find . -name '.git' | xargs rm -rf && \
    # Copy plugin files
    ./install.sh /usr/local/share/nvim/runtime && \
    rm -rf /tmp/*

RUN ln -s /usr/local/bin/nvim /usr/local/bin/vi


###############
# Install YCM #
###############
