# vim:set ft=dockerfile:

# Use LHCb's slc6
FROM hepsw/lhcb-base
USER root

#################
# Update system #
#################

# Make slc6 work inside the LayeredFS
# This is an known bug. Go to the following url for more info:
#   https://docs.oracle.com/cd/E93554_01/E69348/html/uek4-czc_xmc_xt.html
RUN yum install -y yum-plugin-ovl; yum clean all

RUN yum update -y && \
    yum clean all && rm -rf /var/cache/yum


####################
# Add dev packages #
####################

RUN yum install -y \
    autoconf automake \
    bash-completion \
    binutils-devel bzip2-devel bzip2 \
    file \
    gcc gcc-c++ git glibc-devel glibc-static \
    libtool libXpm-devel libXft-devel libXext-devel \
    m4 make \
    ncurses-devel \
    patch \
    readline readline-devel \
    tar texinfo \
    python-pip \
    zsh tmux emacs vim \
    && yum clean all && rm -rf /var/cache/yum


#########################
# Install LHCb packages #
#########################

ENV MYSITEROOT /opt/lhcb-sw
ENV PATH       $MYSITEROOT/usr/bin:$PATH
#ENV CMTCONFIG  x86_64-slc6-gcc49-opt

RUN lbpkr install-project -platforms=all DAVINCI v36r1p2 && \
    /bin/rm -rf $MYSITEROOT/{tmp,targz} && \
    /bin/mkdir ${MYSITEROOT}/{tmp,targz}


###############################
# Load default configurations #
###############################

ADD ./zshrc /home/physicist/.zshrc
ADD ./tmux.conf /home/physicist/.tmux.conf


#############################
# Bootstrap user permission #
#############################

# Add the bootstrap script
ADD ./bootstrap.sh /usr/local/bin

# Make UID and GID ENV, also delete 'builder'
ENV UID 1000
ENV GID 985

CMD ["/usr/local/bin/bootstrap.sh"]
